README.md
Edited README.md to add workflows section and some typical workflows.
=> Update Workflows in README

source/ProSymbolEditor/Config.daml, source/ProSymbolEditor/ProSymbolEditor.csproj
#61 -
ProSymbolEditor -> MilitarySymbolEditor
0.1.0 -> 1.0.0
=> Change Addin Name + Version

source/ProSymbolEditor/Models/MilitaryFieldsInspectorModel.cs, source/ProSymbolEditor/Models/SymbolAttributes/DisplayAttributes.cs, source/ProSymbolEditor/Models/SymbolAttributes/LabelAttributes.cs, source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs, source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs, source/ProSymbolEditor/Views/MilitarySymbolDockpane.xaml
Removed horizontal tables, added vertical property table for modify, text, and coordinate tabs.  The vertical property table is the same found on the favorites tab.
=> Updating tables on tabs to match

source/ProSymbolEditor/Models/DomainCodedValuePair.cs, source/ProSymbolEditor/Models/MilitaryFieldsInspectorModel.cs, source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs, source/ProSymbolEditor/ProSymbolEditor.csproj, source/ProSymbolEditor/Utilities/Extensions.cs, source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs, source/ProSymbolEditor/Views/MilitarySymbolDockpane.xaml
Fixed github issues #66, #22, #29.
=> Fixing github issues

source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs
Issue #94 - fix crash when feature without "symbolset" field selected
=> Issue #94 - fix crash

source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs, source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs
Fix to crash if: 
1. Addin just started and no active symbol and 
2. You click add favorite: 
https://github.com/Esri/military-tools-for-arcgis/issues/63
=> Crash if add fav and no active symbol 

source/ProSymbolEditor/Models/SymbolAttributes/DisplayAttributes.cs, source/ProSymbolEditor/Models/SymbolAttributes/LabelAttributes.cs, source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs, source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs
Prevent adding same/identical favorite more than once:
https://github.com/Esri/military-tools-for-arcgis/issues/63
=> Fix military-tools-for-arcgis issue 63

source/ProSymbolEditor/Config.daml
=> Issue #118 - Bad Addin Tooltip Name

source/ProSymbolEditor/Config.daml
See #118 - updating tooltip text
=> Issue #118 (redo)

source/ProSymbolEditor/MapTools/SelectionMapTool.cs, source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs, source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs, source/ProSymbolEditor/Views/MilitarySymbolDockpane.xaml, source/ProSymbolEditor/Views/MilitarySymbolDockpane.xaml.cs
Issue #65 - Symbol Preview Gap
Issue #70 - Clear search if no map
Issue #78 - Selection Issues
=> Several Milestone Next Issues

source/ProSymbolEditor/MapTools/SelectionMapTool.cs, source/ProSymbolEditor/Models/SelectedFeature.cs, source/ProSymbolEditor/Models/SymbolAttributes/DisplayAttributes.cs, source/ProSymbolEditor/Models/SymbolAttributes/LabelAttributes.cs, source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs, source/ProSymbolEditor/Utilities/ProSymbolUtilities.cs, source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs, source/ProSymbolEditor/Views/MilitarySymbolDockpane.xaml
#93 - better named attributes table
#113 - add tags on saving map-selected features as favorite
#107 (redo) - clear selection not working when not run on UI thread
=> #93 #113 #107(redo)

source/ProSymbolEditor/ProSymbolEditor.csproj, source/ProSymbolEditor/SettingsWindow.xaml, source/ProSymbolEditor/Views/MilitarySymbolDockpane.xaml, source/ProSymbolEditor/app.config, source/SymbolEditorUnitTests/SymbolEditorUnitTests.csproj
Updating Projects to 1.4 and fixes to #124 (Dark Mode)
=> Issue #124 and update to 1 4

source/ProSymbolEditor/AboutWindow.xaml, source/ProSymbolEditor/Config.daml, source/ProSymbolEditor/Properties/AssemblyInfo.cs
Changes:
1. Updated the Pro SDK in the DAML to 1.4
2. Assembly version number to 1.4
3. Removed version number and hyperlinks from About Form - also added OK button to form. (Issue #134 )
=> Update Pro SDK+dll version to 1.4 and update About Form

source/ProSymbolEditor/Config.daml
See: https://github.com/Esri/military-tools-desktop-addins/issues/6
=> Update version to 2.0 (Dev Branch)

source/ProSymbolEditor/Config.daml
See: https://github.com/Esri/military-tools-desktop-addins/issues/6
=> Update version to 2.0

source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs
=> Remove pop-up for non-military features

source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs
#137 - Allow labels to be set to null / empty - in order to allow
clearing the field on Save Edits
=> #137 - Allow labels to be set to null / empty

source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs, source/ProSymbolEditor/Views/MilitarySymbolDockpane.xaml
#133 Fix Tags visibility in Dark Mode
=> #133 Fix Tags visibility in Dark Mode

source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs, source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs
=> Fix image flipped on export

README.md, source/ProSymbolEditor/Config.daml, source/ProSymbolEditor/MapTools/CoordinateMapTool.cs, source/ProSymbolEditor/MapTools/DrawFeatureSketchTool.cs, source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs, source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs
Note: breaking change - code will not be backward compatible
=> Update to Pro 2.0

source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs, source/ProSymbolEditor/Utilities/ProSymbolUtilities.cs, source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs, source/ProSymbolEditor/Views/MilitarySymbolDockpane.xaml
=> Favorite to feature template

source/ProSymbolEditor/ProSymbolEditor.csproj
Updating the Build number to the addin to allow it to be created in the properties of the add-in by Jenkins
=> Adding the Build Number

source/ProSymbolEditor/Config.daml
Addresses #215 https://github.com/Esri/military-tools-desktop-addins/issues/44
=> Update target version - Addresses #215

source/ProSymbolEditor/Converters/StringCharacterValueConverter.cs, source/ProSymbolEditor/MapTools/CoordinateMapTool.cs, source/ProSymbolEditor/MapTools/DrawFeatureSketchTool.cs, source/ProSymbolEditor/Models/MilitaryOverlayDataModel.cs, source/ProSymbolEditor/Models/SelectedFeature.cs, source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs, source/ProSymbolEditor/Models/SymbolSetMappings.cs, source/ProSymbolEditor/ProSymbolEditor.csproj, source/ProSymbolEditor/Utilities/ProSymbolUtilities.cs, source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs
Change made to address Static Code Analyzer (SCA) Issues added to the repo.
See Issues: #197 #198 #199 #200 #201 - https://github.com/Esri/military-symbol-editor-addin-wpf/labels/T-SCA
=> Static Code Analyzer Issues

source/ProSymbolEditor/Models/SymbolSetMappings.cs, source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs
Addresses: #214 - Select on Modify Tab causes crash if expected field is null
=> #214 - Select on Modify Tab causes crash if expected field is null

source/ProSymbolEditor/Utilities/ProSymbolUtilities.cs, source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs
Address Issue #195 - save project when Military Overlay lpkx is added
=> Issue #195 save project when Military Overlay lpkx is added

.gitignore, source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs
=> Add check for data model to add to map button

source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs
Addresses:
#253 - sort search results alphabetically by name
#186 - update current symbol with 1st symbol returned from search
=> Addresses #253 and #186

source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs
#292 redo - Completely remove 'MAP_SELECTION' tag
=> #292 redo - Completely remove 'MAP_SELECTION' tag 

source/ProSymbolEditor/MapTools/SelectionMapTool.cs, source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs, source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs, source/ProSymbolEditor/Views/CoordinateView.xaml, source/ProSymbolEditor/Views/FavoritesView.xaml, source/ProSymbolEditor/Views/LabelView.xaml, source/ProSymbolEditor/Views/MilitarySymbolDockpane.xaml, source/ProSymbolEditor/Views/SearchView.xaml, source/ProSymbolEditor/Views/SymbolView.xaml
Address Issue #204 : 
1. Remove the modify tab
2. Move Select Button
3. Change Select to single/point-select 
Should look like this after PR:
=> Remove modify tab - #204

source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs
See Issue #320 - addin to add-in consistency
Also tried to make "data model" consistent
=> Issue #320 - addin to add-in

source/ProSymbolEditor/Models/SymbolAttributes/LabelAttributes.cs, source/ProSymbolEditor/Views/MilitarySymbolDockpane.xaml
This addresses the [new issue](https://github.com/Esri/military-symbology/issues/327#issuecomment-454837460) @dfoll found when testing #327
=> Addresses new issue in #327

README.md
=> Added ref to APP-6(D)

README.md
Remove content ref the Modify tab
=> Remove content ref the Modify tab

source/ProSymbolEditor/Models/SymbolAttributes/LabelAttributes.cs, source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs, source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs
Addresses #345 
1. Fixes bug
2. Adds switch to control when UI Length validation happens
3. Adds some exception handling to favorites deserialization
=> Address #345 - fix max length labels failing on selection

README.md, source/ProSymbolEditor/Models/MilitaryFieldsInspectorModel.cs, source/ProSymbolEditor/Models/SymbolAttributes/LabelAttributes.cs, source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs, source/ProSymbolEditor/Utilities/ProSymbolUtilities.cs, source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs
MSE issues #330, #345 included in Military Tools Release 3.3.1
http://solutions.arcgis.com/defense/help/military-tools/resources/february-2019-military-tools-for-arcgis.htm
=> Update Master to Military Tools Release 3.3.1

military-overlay/utils-source-and-test-data/schema-creation-utilities/template-gdb-toolbox/scripts/ExportGDBFieldsToFolder.py
Dataset names were unnecessarily hard-coded in script
=> Fix bug in export fields script

source/ProSymbolEditor/Models/MilitaryFieldsInspectorModel.cs, source/ProSymbolEditor/Models/MilitaryOverlayDataModel.cs, source/ProSymbolEditor/Models/SymbolAttributes/DisplayAttributes.cs, source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs, source/ProSymbolEditor/Models/SymbolSetMappings.cs, source/ProSymbolEditor/ProSymbolEditor.csproj, source/ProSymbolEditor/SettingsWindow.xaml.cs, source/ProSymbolEditor/Utilities/ProSymbolUtilities.cs, source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs
=> Changes for #332 to add 2525C support

source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs, source/ProSymbolEditor/Views/FavoritesView.xaml, source/ProSymbolEditor/Views/SearchView.xaml
=> #381- Reset state better when favorite deleted

source/ProSymbolEditor/Models/SymbolAttributes/DisplayAttributes.cs, source/ProSymbolEditor/Models/SymbolAttributes/SymbolAttributeSet.cs, source/ProSymbolEditor/Utilities/ProSymbolUtilities.cs, source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs, source/ProSymbolEditor/Views/CoordinateView.xaml, source/ProSymbolEditor/Views/LabelView.xaml, source/ProSymbolEditor/Views/ModifyView.xaml, source/ProSymbolEditor/Views/SearchView.xaml, source/ProSymbolEditor/Views/SearchView.xaml.cs, source/ProSymbolEditor/Views/SymbolView.xaml
See: #178 #386
Adds ability to:
1. Search for symbol by full SIDC #178 
2. Copy/Paste from Attribute Table, add SymbolIdCode attribute to the table - #386
=> Add search by SIDC and copy/paste from attribute table
